name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-LIL-2-1-chocolatine-gianni.henriques.git
  EXECUTABLES: "antman/antman,giantman/giantman"

jobs:
  checking_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Coding Style checker
        run: |
          check.sh $(pwd) $(pwd)
          while read Line; \
          do \
          ARG1=$(echo $Line | cut -d: -f1); \
          ARG2=$(echo $Line | cut -d: -f2); \
          ARG3=$(echo $Line | cut -d: -f3); \
          ARG4=$(echo $Line | cut -d: -f4); \
          echo "::error file=$ARG1, line=$ARG2:: $ARG3 $ARG4"; \
          done < coding-style-reports.log
          if [ -s coding-style-reports.log ]; then
            exit 1
          fi
  
  check_program_compilation:
    needs: checking_coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Compile the program
        run: timeout 2m make
      - name: Clean the useless files
        run: make clean
      - name: Check each executables
        run: |
          IFS=','
          for value in $EXECUTABLES; do
            if [ -e $value ]; then
              exit 0
            else
              exit 1
            fi
          done

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run unit tests
        run: timeout 2m make tests_run

  push_to_mirror:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: $MIRROR_URL
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}